# -*- coding: utf-8 -*-
"""
/***************************************************************************
 INDEDialog
                                 A QGIS plugin
 This plugin allows connection to all ows services available in Brazil National Spatial Data Infrastructure
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-10-26
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Julierme G Pinheiro / Leandro França
        email                : contato@geoone.com.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.PyQt import uic, QtWidgets

# (Opcional, mas recomendado) se você tiver um .qrc compilado:
# from . import resources_rc

UI_FILE = os.path.join(os.path.dirname(__file__), 'INDE_dialog_base.ui')

# Compat PyQt6/5: sem resource_suffix; no PyQt5 ainda dá para usar from_imports, se quiser.
try:
    # PyQt6: assinatura simples
    FORM_CLASS, _ = uic.loadUiType(UI_FILE)
except TypeError:
    # PyQt5 (fallback)
    FORM_CLASS, _ = uic.loadUiType(UI_FILE, from_imports=False)


class INDEDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(INDEDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
